// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqxRRbQxeOW40z8OAcPrcL2TlZW8MyiQI',
    appId: '1:523153422644:web:6f4a6fef33ad8b653ccd61',
    messagingSenderId: '523153422644',
    projectId: 'notes-with-bloc-9c317',
    authDomain: 'notes-with-bloc-9c317.firebaseapp.com',
    storageBucket: 'notes-with-bloc-9c317.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADOrO_hdIQnWTnxmKq-lqYlI5iZPq9FuM',
    appId: '1:523153422644:android:3e8e1b8726af2e8c3ccd61',
    messagingSenderId: '523153422644',
    projectId: 'notes-with-bloc-9c317',
    storageBucket: 'notes-with-bloc-9c317.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBebD36WnzTIGvoU5R82OAmqjLeB0KMa_U',
    appId: '1:523153422644:ios:68256966d9c0ae2e3ccd61',
    messagingSenderId: '523153422644',
    projectId: 'notes-with-bloc-9c317',
    storageBucket: 'notes-with-bloc-9c317.appspot.com',
    iosBundleId: 'com.example.blocFireNotes',
  );
}
